language: minimal

services: docker

env:
    - DOCKER_COMPOSE_VERSION=1.23.2

before_script:
    - docker -v && docker-compose -v
    - sudo rm /usr/local/bin/docker-compose
    - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - openssl aes-256-cbc -K $encrypted_40c75d714fd1_key -iv $encrypted_40c75d714fd1_iv -in ./k8s/aws/udagram-dev-kubeconfig.enc -out ./k8s/aws/udagram-dev-kubeconfig -d
    - export KUBECONFIG=./k8s/aws/udagram-dev-kubeconfig

script:
    # - docker-compose -f docker-compose-build.yaml build --parallel
    - cat $KUBECONFIG

deploy:
    provider: script
    script: bash deploy.sh
    on:
        branch: travis
