version: "3"
services:
    reverseproxy:
        image: vinayakvivekk/udacity-reverse-proxy
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - backend-user
            - backend-feed
    backend-user:
        image: vinayakvivekk/udacity-user-restapi
        volumes:
            - $HOME/.aws:/root/.aws
        environment:
            DB_USERNAME: $DB_USERNAME
            DB_PASSWORD: $DB_PASSWORD
            DB_NAME: $DB_NAME
            DB_HOST: $DB_HOST
            AWS_REGION: $AWS_REGION
            AWS_PROFILE: $AWS_PROFILE
            AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"
    backend-feed:
        image: vinayakvivekk/udacity-feed-restapi
        volumes:
            - $HOME/.aws:/root/.aws
        environment:
            DB_USERNAME: $DB_USERNAME
            DB_PASSWORD: $DB_PASSWORD
            DB_NAME: $DB_NAME
            DB_HOST: $DB_HOST
            AWS_REGION: $AWS_REGION
            AWS_PROFILE: $AWS_PROFILE
            AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"
    frontend:
        image: vinayakvivekk/udacity-frontend
        ports:
            - "8100:80"